# Generated by Django 4.2 on 2023-04-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_feed'),
        ('recomments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='comments.comment'),
        ),
    ]
