# Generated by Django 4.2 on 2023-04-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_remove_feed_feed_comment'),
        ('comments', '0004_rename_feed_comment_all_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='all_feed',
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_feed', to='feeds.feed'),
            preserve_default=False,
        ),
    ]
