# Generated by Django 4.2 on 2023-04-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_remove_feed_feed_comment'),
        ('comments', '0005_remove_comment_all_feed_comment_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='feeds.feed'),
        ),
    ]
