# Generated by Django 4.2 on 2023-04-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_alter_comment_user_recomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
