# Generated by Django 4.2 on 2023-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auth_sms",
            options={"verbose_name_plural": "Auth_sms"},
        ),
        migrations.AlterField(
            model_name="auth_sms",
            name="auth_number",
            field=models.IntegerField(editable=False, verbose_name="인증 번호"),
        ),
        migrations.AlterModelTable(
            name="auth_sms",
            table=None,
        ),
    ]
