# Generated by Django 4.2 on 2023-05-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_sms", "0002_alter_auth_sms_options_alter_auth_sms_auth_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Auth_sms",
        ),
    ]
