# Generated by Django 4.2 on 2023-04-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0003_remove_group_coach"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=13, unique=True)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("is_signup", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
