# Generated by Django 4.2 on 2023-04-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_feed'),
        ('feeds', '0006_remove_feed_feed_comment'),
        ('likes', '0003_commentlike_feedlike_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlike', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedlike', to='feeds.feed'),
        ),
    ]
