# Generated by Django 4.2 on 2023-04-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_alter_comment_user_recomment"),
        ("likes", "0004_alter_commentlike_comment_alter_feedlike_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentlike",
            name="recomment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommentlike",
                to="comments.recomment",
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentlike",
                to="comments.comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("user", "comment"), name="unique_comment_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("user", "recomment"), name="unique_recomment_like"
            ),
        ),
    ]
