# Generated by Django 4.2 on 2023-04-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_remove_category_feed'),
        ('feeds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
