# Generated by Django 4.2 on 2023-04-11 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feed_all_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='all_comments',
            new_name='feed_comment',
        ),
    ]
