# Generated by Django 4.2 on 2023-04-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_rename_all_comments_feed_feed_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_comment',
        ),
    ]
