# Generated by Django 4.2 on 2023-04-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_group_name"),
        ("feeds", "0006_remove_feed_feed_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.group",
            ),
        ),
    ]
