# Generated by Django 4.2 on 2023-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0007_alter_feed_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="title",
        ),
        migrations.AlterField(
            model_name="feed",
            name="description",
            field=models.TextField(),
        ),
    ]
