# Generated by Django 4.2 on 2023-04-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_alter_category_group_delete_initial_categroy"),
        ("groups", "0004_alter_group_name"),
        ("feeds", "0008_remove_feed_title_alter_feed_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.group"
            ),
        ),
    ]
