# Generated by Django 4.2 on 2023-04-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_group_name"),
        ("feeds", "0009_alter_feed_category_alter_feed_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.group",
            ),
        ),
    ]
