# Generated by Django 4.2 on 2023-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0010_alter_feed_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="title",
            field=models.CharField(default="title", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feed",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
