# Generated by Django 4.2 on 2023-04-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0008_alter_category_options"),
        ("feeds", "0011_feed_title_alter_feed_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to="categories.category",
            ),
        ),
    ]
