# Generated by Django 4.2 on 2023-04-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterlists', '0003_remove_letterlist_message_remove_letterlist_user_and_more'),
        ('letters', '0004_remove_letter_receiver_remove_letter_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='letterlists.letterlist'),
        ),
    ]
