# Generated by Django 4.2 on 2023-04-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_name'),
        ('categories', '0004_category_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_categroy',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('groups.group',),
        ),
    ]
