# Generated by Django 4.2 on 2023-04-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_group_name"),
        ("categories", "0006_category_unique_category_name_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="groups.group",
            ),
        ),
        migrations.DeleteModel(
            name="initial_categroy",
        ),
    ]
