# Generated by Django 4.2 on 2023-04-09 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letterlists', '0002_rename_letter_letterlist_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterlist',
            name='message',
        ),
        migrations.RemoveField(
            model_name='letterlist',
            name='user',
        ),
        migrations.AddField(
            model_name='letterlist',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letterlist',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
