# Generated by Django 4.2 on 2023-04-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0006_remove_letter_list_letter_receiver_letter_sender"),
        (
            "letterlists",
            "0003_remove_letterlist_message_remove_letterlist_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letterlist",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="letterlist",
            name="sender",
        ),
        migrations.AddField(
            model_name="letterlist",
            name="letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="letters.letter",
            ),
        ),
    ]
