# Generated by Django 4.2 on 2023-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0006_remove_letter_list_letter_receiver_letter_sender"),
        (
            "letterlists",
            "0004_remove_letterlist_receiver_remove_letterlist_sender_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letterlist",
            name="letter",
        ),
        migrations.AddField(
            model_name="letterlist",
            name="letter",
            field=models.ManyToManyField(
                related_name="letterlist", to="letters.letter"
            ),
        ),
    ]
