# Generated by Django 4.2 on 2023-04-24 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letterlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="delete_by",
            field=models.ManyToManyField(
                related_name="deleted_letters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
