# Generated by Django 4.2 on 2023-04-27 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letterlist", "0003_alter_letter_delete_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="delete_by",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_letters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
