# Generated by Django 4.2 on 2023-04-27 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letterlist", "0004_alter_letter_delete_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterlist",
            name="ignore_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="deleted_letter_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
