# Generated by Django 4.2 on 2023-04-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_coach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="coach",
        ),
    ]
