# Generated by Django 4.2 on 2023-04-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_remove_group_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
